<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Dell7" ignored="0" name="Default test" tests="1" failures="1" timestamp="17 Apr 2020 04:47:06 GMT" time="4.065" errors="0">
  <testcase name="ExecuteTests" time="0.014" classname="StrangerTCs.TestPage">
    <failure type="java.lang.Error" message="Unresolved compilation problems: 
	StrangerPage cannot be resolved
	StrangerPage cannot be resolved
	StrangerPage cannot be resolved
	StrangerPage cannot be resolved
	StrangerPage cannot be resolved
	StrangerPage cannot be resolved
	StrangerPage cannot be resolved
	StrangerPage cannot be resolved
">
      <![CDATA[java.lang.Error: Unresolved compilation problems: 
StrangerPage cannot be resolved
StrangerPage cannot be resolved
StrangerPage cannot be resolved
StrangerPage cannot be resolved
StrangerPage cannot be resolved
StrangerPage cannot be resolved
StrangerPage cannot be resolved
StrangerPage cannot be resolved

at StrangerTCs.TestPage.ExecuteTests(TestPage.java:29)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- ExecuteTests -->
</testsuite> <!-- Default test -->
